name: cctv_test
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.11.4
  - expat=2.7.3
  - libffi=3.4.4
  - libzlib=1.3.1
  - openssl=3.0.18
  - pip=25.3
  - python=3.10.19
  - setuptools=80.9.0
  - sqlite=3.51.0
  - tk=8.6.15
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - absl-py==2.3.1
      - albucore==0.0.24
      - albumentations==2.0.8
      - annotated-types==0.7.0
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - click==8.3.1
      - colorama==0.4.6
      - contourpy==1.3.2
      - cssselect2==0.8.0
      - cycler==0.12.1
      - darkdetect==0.7.1
      - filelock==3.19.1
      - fire==0.7.1
      - fonttools==4.61.0
      - freetype-py==2.5.1
      - fsspec==2025.9.0
      - grpcio==1.76.0
      - idna==3.11
      - jinja2==3.1.6
      - joblib==1.5.2
      - kiwisolver==1.4.9
      - lapx==0.9.2
      - lxml==6.0.2
      - markdown==3.10
      - markupsafe==2.1.5
      - matplotlib==3.10.7
      - mpmath==1.3.0
      - networkx==3.3
      - numpy==2.1.2
      - opencv-python==4.11.0.86
      - packaging==25.0
      - pandas==2.3.3
      - pillow==11.3.0
      - polars==1.35.2
      - polars-runtime-32==1.35.2
      - protobuf==6.33.1
      - psutil==7.1.3
      - pybboxes==0.1.6
      - pycairo==1.29.0
      - pycocotools==2.0.10
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pyparsing==3.2.5
      - pyqt5==5.15.11
      - pyqt5-qt5==5.15.2
      - pyqt5-sip==12.17.1
      - pyqtdarktheme==2.1.0
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - reportlab==4.4.5
      - requests==2.32.5
      - rlpycairo==0.4.0
      - sahi==0.11.36
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - scour==0.38.2
      - shapely==2.1.2
      - simsimd==6.5.3
      - six==1.17.0
      - stringzilla==4.4.0
      - svglib==1.6.0
      - sympy==1.13.1
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - termcolor==3.2.0
      - terminaltables==3.1.10
      - threadpoolctl==3.6.0
      - tinycss2==1.5.1
      - torch==2.5.1
      - torchaudio==2.5.1
      - torchvision==0.20.1
      - tqdm==4.67.1
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - ultralytics==8.3.233
      - ultralytics-thop==2.0.18
      - urllib3==2.5.0
      - webencodings==0.5.1
      - werkzeug==3.1.4
